title: "Your Name"
description: "Data Science Portfolio"
theme: jekyll-theme-minimal

# Optional social links
author: yourusername
email: your@email.com
linkedin_username: your-linkedin
github_username: yourusername
